
Brute_Tankmech_Name = "Taurus Cannon",
Brute_Tankmech_Description = "Shoot a powerful projectile that damages and pushes the target.", 
Brute_Tankmech_Upgrade1 = "+1 Damage",
Brute_Tankmech_Upgrade2 = "+1 Damage",
Brute_Tankmech_A_Description = "Increases damage by 1.",
Brute_Tankmech_B_Description = "Increases damage by 1.",

Brute_Jetmech_Name = "Strafe",
Brute_Jetmech_Description = "Fly over a target, dropping an explosive smoke bomb.", 
Brute_Jetmech_Upgrade1 = "+1 Damage",
Brute_Jetmech_Upgrade2 = "+1 Range",
Brute_Jetmech_A_Description = "Increases damage by 1.",
Brute_Jetmech_B_Description = "Allows jumping over and attacking an additional target.",

Brute_Mirrorshot_Name = "Mirror Cannon",
Brute_Mirrorshot_Description = "Fire two projectiles in opposite directions.", 
Brute_Mirrorshot_Upgrade1 = "+1 Damage",
Brute_Mirrorshot_Upgrade2 = "+1 Damage",
Brute_Mirrorshot_A_Description = "Increases damage by 1.",
Brute_Mirrorshot_B_Description = "Increases damage by 1.",

Brute_PhaseShot_Name = "Phase Cannon",
Brute_PhaseShot_Description = "Shoot a projectile that phases through objects.", 
Brute_PhaseShot_Upgrade1 = "+1 Damage",
Brute_PhaseShot_Upgrade2 = "+1 Damage",
Brute_PhaseShot_A_Description = "Increases damage by 1.",
Brute_PhaseShot_B_Description = "Increases damage by 1.",

Brute_Grapple_Name = "Grappling Hook",
Brute_Grapple_Description = "Use a grapple to pull Mech towards objects, or units to the Mech.", 
Brute_Grapple_Upgrade1 = "",
Brute_Grapple_Upgrade2 = "",
Brute_Grapple_A_Description = "",
Brute_Grapple_B_Description = "",

Brute_Shrapnel_Name = "Def. Shrapnel",
Brute_Shrapnel_Description = "Fire a projectile that does no damage but pushes the tiles around the target.", 
Brute_Shrapnel_Upgrade1 = "",
Brute_Shrapnel_Upgrade2 = "",
Brute_Shrapnel_A_Description = "",
Brute_Shrapnel_B_Description = "",

Brute_Beetle_Name = "Ramming Engines",
Brute_Beetle_Description = "Fly in a line and slam into the target, pushing it and hurting yourself.", 
Brute_Beetle_Upgrade1 = "+1 Damage Each",
Brute_Beetle_Upgrade2 = "+1 Damage",
Brute_Beetle_A_Description = "Increases damage to target and to self damage by 1.",
Brute_Beetle_B_Description = "Increases damage to target by 1.",

Brute_Unstable_Name = "Unstable Cannon",
Brute_Unstable_Description = "Powerful projectile that causes damage to the shooter as well as the target.", 
Brute_Unstable_Upgrade1 = "+1 Damage Each",
Brute_Unstable_Upgrade2 = "+1 Damage",
Brute_Unstable_A_Description = "Increases target damage by 1 and increase self-damage by 1.",
Brute_Unstable_B_Description = "Increases target damage by 1.",

Brute_Heavyrocket_Name = "Heavy Rocket",
Brute_Heavyrocket_Description = "Fire a projectile that heavily damages a target and pushes adjacent tiles.", 
Brute_Heavyrocket_Upgrade1 = "+1 Use",
Brute_Heavyrocket_Upgrade2 = "+2 Damage",
Brute_Heavyrocket_A_Description = "Increases uses by 1.",
Brute_Heavyrocket_B_Description = "Increases damage by 2.",

Brute_Splitshot_Name = "Split Shot",
Brute_Splitshot_Description = "Shoot a projectile that damages and pushes the hit tile and the tiles to its left and right.", 
Brute_Splitshot_Upgrade1 = "+1 Use",
Brute_Splitshot_Upgrade2 = "+1 Damage",
Brute_Splitshot_A_Description = "Increases uses by 1.",
Brute_Splitshot_B_Description = "Increases damage by 2.",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

_Name = "",
_Description = "", 
_Upgrade1 = "",
_Upgrade2 = "",
_A_Description = "",
_B_Description = "",

